package com.newray.base.dict.model;

// Generated 2013-5-11 15:43:03 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * 字典明细
 * DictLibrary generated by hbm2java
 */
@Entity
@Table(name = "DICT_LIBRARY", schema = "NEWRAY")
public class DictLibrary implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private DictLibraryId id;
	private String itemname;
	private String bankno;
	private String sortno;
	private String isinuse;
	private String itemdescribe;
	private String itemattribute;
	private String relativecode;
	private String attribute1;
	private String attribute2;
	private String attribute3;
	private String attribute4;
	private String attribute5;
	private String attribute6;
	private String attribute7;
	private String attribute8;
	private String inputuser;
	private String inputorg;
	private String inputdate;
	private String updateuser;
	private String updatedate;
	private String remark;
	private String helptext;

	public DictLibrary() {
	}

	public DictLibrary(DictLibraryId id) {
		this.id = id;
	}

	public DictLibrary(DictLibraryId id, String itemname, String bankno,
			String sortno, String isinuse, String itemdescribe,
			String itemattribute, String relativecode, String attribute1,
			String attribute2, String attribute3, String attribute4,
			String attribute5, String attribute6, String attribute7,
			String attribute8, String inputuser, String inputorg,
			String inputdate, String updateuser, String updatedate,
			String remark, String helptext) {
		this.id = id;
		this.itemname = itemname;
		this.bankno = bankno;
		this.sortno = sortno;
		this.isinuse = isinuse;
		this.itemdescribe = itemdescribe;
		this.itemattribute = itemattribute;
		this.relativecode = relativecode;
		this.attribute1 = attribute1;
		this.attribute2 = attribute2;
		this.attribute3 = attribute3;
		this.attribute4 = attribute4;
		this.attribute5 = attribute5;
		this.attribute6 = attribute6;
		this.attribute7 = attribute7;
		this.attribute8 = attribute8;
		this.inputuser = inputuser;
		this.inputorg = inputorg;
		this.inputdate = inputdate;
		this.updateuser = updateuser;
		this.updatedate = updatedate;
		this.remark = remark;
		this.helptext = helptext;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "dictno", column = @Column(name = "DICTNO", nullable = false, length = 32)),
			@AttributeOverride(name = "itemno", column = @Column(name = "ITEMNO", nullable = false, length = 32)) })
	public DictLibraryId getId() {
		return this.id;
	}

	public void setId(DictLibraryId id) {
		this.id = id;
	}

	@Column(name = "ITEMNAME", length = 250)
	public String getItemname() {
		return this.itemname;
	}

	public void setItemname(String itemname) {
		this.itemname = itemname;
	}

	@Column(name = "BANKNO", length = 32)
	public String getBankno() {
		return this.bankno;
	}

	public void setBankno(String bankno) {
		this.bankno = bankno;
	}

	@Column(name = "SORTNO", length = 32)
	public String getSortno() {
		return this.sortno;
	}

	public void setSortno(String sortno) {
		this.sortno = sortno;
	}

	@Column(name = "ISINUSE", length = 18)
	public String getIsinuse() {
		return this.isinuse;
	}

	public void setIsinuse(String isinuse) {
		this.isinuse = isinuse;
	}

	@Column(name = "ITEMDESCRIBE", length = 800)
	public String getItemdescribe() {
		return this.itemdescribe;
	}

	public void setItemdescribe(String itemdescribe) {
		this.itemdescribe = itemdescribe;
	}

	@Column(name = "ITEMATTRIBUTE", length = 800)
	public String getItemattribute() {
		return this.itemattribute;
	}

	public void setItemattribute(String itemattribute) {
		this.itemattribute = itemattribute;
	}

	@Column(name = "RELATIVECODE", length = 1600)
	public String getRelativecode() {
		return this.relativecode;
	}

	public void setRelativecode(String relativecode) {
		this.relativecode = relativecode;
	}

	@Column(name = "ATTRIBUTE1", length = 800)
	public String getAttribute1() {
		return this.attribute1;
	}

	public void setAttribute1(String attribute1) {
		this.attribute1 = attribute1;
	}

	@Column(name = "ATTRIBUTE2", length = 250)
	public String getAttribute2() {
		return this.attribute2;
	}

	public void setAttribute2(String attribute2) {
		this.attribute2 = attribute2;
	}

	@Column(name = "ATTRIBUTE3", length = 250)
	public String getAttribute3() {
		return this.attribute3;
	}

	public void setAttribute3(String attribute3) {
		this.attribute3 = attribute3;
	}

	@Column(name = "ATTRIBUTE4", length = 250)
	public String getAttribute4() {
		return this.attribute4;
	}

	public void setAttribute4(String attribute4) {
		this.attribute4 = attribute4;
	}

	@Column(name = "ATTRIBUTE5", length = 250)
	public String getAttribute5() {
		return this.attribute5;
	}

	public void setAttribute5(String attribute5) {
		this.attribute5 = attribute5;
	}

	@Column(name = "ATTRIBUTE6", length = 250)
	public String getAttribute6() {
		return this.attribute6;
	}

	public void setAttribute6(String attribute6) {
		this.attribute6 = attribute6;
	}

	@Column(name = "ATTRIBUTE7", length = 250)
	public String getAttribute7() {
		return this.attribute7;
	}

	public void setAttribute7(String attribute7) {
		this.attribute7 = attribute7;
	}

	@Column(name = "ATTRIBUTE8", length = 250)
	public String getAttribute8() {
		return this.attribute8;
	}

	public void setAttribute8(String attribute8) {
		this.attribute8 = attribute8;
	}

	@Column(name = "INPUTUSER", length = 32)
	public String getInputuser() {
		return this.inputuser;
	}

	public void setInputuser(String inputuser) {
		this.inputuser = inputuser;
	}

	@Column(name = "INPUTORG", length = 32)
	public String getInputorg() {
		return this.inputorg;
	}

	public void setInputorg(String inputorg) {
		this.inputorg = inputorg;
	}

	@Column(name = "INPUTDATE", length = 20)
	public String getInputdate() {
		return this.inputdate;
	}

	public void setInputdate(String inputdate) {
		this.inputdate = inputdate;
	}

	@Column(name = "UPDATEUSER", length = 32)
	public String getUpdateuser() {
		return this.updateuser;
	}

	public void setUpdateuser(String updateuser) {
		this.updateuser = updateuser;
	}

	@Column(name = "UPDATEDATE", length = 20)
	public String getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(String updatedate) {
		this.updatedate = updatedate;
	}

	@Column(name = "REMARK", length = 250)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "HELPTEXT", length = 250)
	public String getHelptext() {
		return this.helptext;
	}

	public void setHelptext(String helptext) {
		this.helptext = helptext;
	}

}
