package com.newray.base.dict.model;

// Generated 2013-5-11 15:43:03 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DictLibraryId generated by hbm2java
 */
@Embeddable
public class DictLibraryId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String dictno;
	private String itemno;

	public DictLibraryId() {
	}

	public DictLibraryId(String dictno, String itemno) {
		this.dictno = dictno;
		this.itemno = itemno;
	}

	@Column(name = "DICTNO", nullable = false, length = 32)
	public String getDictno() {
		return this.dictno;
	}

	public void setDictno(String dictno) {
		this.dictno = dictno;
	}

	@Column(name = "ITEMNO", nullable = false, length = 32)
	public String getItemno() {
		return this.itemno;
	}

	public void setItemno(String itemno) {
		this.itemno = itemno;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DictLibraryId))
			return false;
		DictLibraryId castOther = (DictLibraryId) other;

		return ((this.getDictno() == castOther.getDictno()) || (this
				.getDictno() != null && castOther.getDictno() != null && this
				.getDictno().equals(castOther.getDictno())))
				&& ((this.getItemno() == castOther.getItemno()) || (this
						.getItemno() != null && castOther.getItemno() != null && this
						.getItemno().equals(castOther.getItemno())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getDictno() == null ? 0 : this.getDictno().hashCode());
		result = 37 * result
				+ (getItemno() == null ? 0 : this.getItemno().hashCode());
		return result;
	}

}
